package resolvconf

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// writeFixture builds a throwaway root with the given resolv.conf content.
// Everything the write tests touch lives under t.TempDir(), never under /etc.
func writeFixture(t *testing.T, content string) string {
	t.Helper()
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "etc"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, DefaultPath), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return root
}

const sample = `# Managed by hand
search home.arpa lab.internal
nameserver 192.168.1.1
nameserver 9.9.9.9
options ndots:2
`

func TestNameserversAndValues(t *testing.T) {
	conf, err := Load(writeFixture(t, sample))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if got := conf.Nameservers(); !reflect.DeepEqual(got, []string{"192.168.1.1", "9.9.9.9"}) {
		t.Errorf("nameservers = %v", got)
	}
	if got := conf.Values("search"); !reflect.DeepEqual(got, []string{"home.arpa", "lab.internal"}) {
		t.Errorf("search = %v", got)
	}
	if got := conf.Values("options"); !reflect.DeepEqual(got, []string{"ndots:2"}) {
		t.Errorf("options = %v", got)
	}
}

func TestSetNameserversKeepsEverythingElse(t *testing.T) {
	root := writeFixture(t, sample)
	conf, err := Load(root)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}

	conf.SetNameservers([]string{"1.1.1.1", "192.168.1.1", "2606:4700:4700::1111"})
	if err := conf.Save(); err != nil {
		t.Fatalf("Save: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(root, DefaultPath))
	if err != nil {
		t.Fatal(err)
	}
	got := string(data)
	for _, keep := range []string{"# Managed by hand", "search home.arpa lab.internal", "options ndots:2"} {
		if !strings.Contains(got, keep) {
			t.Errorf("rewrite dropped %q\nfile:\n%s", keep, got)
		}
	}
	if strings.Contains(got, "9.9.9.9") {
		t.Errorf("removed nameserver survived the rewrite\nfile:\n%s", got)
	}

	// The new block must sit where the old one was, before `options`.
	nsIndex := strings.Index(got, "nameserver 1.1.1.1")
	optIndex := strings.Index(got, "options ndots:2")
	if nsIndex < 0 || optIndex < 0 || nsIndex > optIndex {
		t.Errorf("nameserver block moved out of place\nfile:\n%s", got)
	}

	reloaded, err := Load(root)
	if err != nil {
		t.Fatalf("reload: %v", err)
	}
	want := []string{"1.1.1.1", "192.168.1.1", "2606:4700:4700::1111"}
	if got := reloaded.Nameservers(); !reflect.DeepEqual(got, want) {
		t.Errorf("after reload nameservers = %v, want %v", got, want)
	}
}

func TestSetNameserversAppendsWhenFileHasNone(t *testing.T) {
	root := writeFixture(t, "search home.arpa\n")
	conf, err := Load(root)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	conf.SetNameservers([]string{"1.1.1.1"})
	if err := conf.Save(); err != nil {
		t.Fatalf("Save: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(root, DefaultPath))
	if got := string(data); got != "search home.arpa\nnameserver 1.1.1.1\n" {
		t.Errorf("file = %q", got)
	}
}

func TestSaveRefusesFileOwnedByAResolverDaemon(t *testing.T) {
	root := writeFixture(t, "# Generated by NetworkManager\nnameserver 1.1.1.1\n")
	conf, err := Load(root)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if got := conf.ManagedBy(); got != "NetworkManager" {
		t.Fatalf("ManagedBy = %q, want NetworkManager", got)
	}

	conf.SetNameservers([]string{"8.8.8.8"})
	err = conf.Save()
	if err == nil {
		t.Fatal("Save succeeded on a file owned by NetworkManager")
	}
	if !strings.Contains(err.Error(), "NetworkManager") {
		t.Errorf("err = %v, want it to name the owner", err)
	}
	// And the file has to be untouched.
	data, _ := os.ReadFile(filepath.Join(root, DefaultPath))
	if !strings.Contains(string(data), "nameserver 1.1.1.1") {
		t.Errorf("file was modified despite the refusal: %q", data)
	}
}

func TestManagedByDetectsSystemdResolvedSymlink(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "etc"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "run/systemd/resolve"), 0o755); err != nil {
		t.Fatal(err)
	}
	stub := filepath.Join(root, "run/systemd/resolve/stub-resolv.conf")
	if err := os.WriteFile(stub, []byte("nameserver 127.0.0.53\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(stub, filepath.Join(root, DefaultPath)); err != nil {
		t.Fatal(err)
	}

	conf, err := Load(root)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if got := conf.ManagedBy(); got != "systemd-resolved" {
		t.Errorf("ManagedBy = %q, want systemd-resolved", got)
	}
}

func TestWriteFileFallsBackWhenRenameIsImpossible(t *testing.T) {
	// A read-only directory makes CreateTemp fail, which is the path the
	// container hits from the other direction (bind-mounted resolv.conf).
	// Either way the caller must get a real error, not a silent no-op.
	root := t.TempDir()
	etc := filepath.Join(root, "etc")
	if err := os.MkdirAll(etc, 0o755); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(root, DefaultPath)
	if err := os.WriteFile(path, []byte("nameserver 1.1.1.1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(etc, 0o555); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { os.Chmod(etc, 0o755) })

	if err := writeFile(path, []byte("nameserver 8.8.8.8\n"), 0o644); err != nil {
		t.Fatalf("in-place write failed: %v", err)
	}
	data, _ := os.ReadFile(path)
	if string(data) != "nameserver 8.8.8.8\n" {
		t.Errorf("file = %q", data)
	}
}
